name: ssh-keygen

on:
  push:
  schedule:
    - cron: '18 19 29 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |-
          go get -u all
          cat go.*
          go build -ldflags="-s -w" -trimpath -buildvcs=false -o ./keygen
        env:
          CGO_ENABLED: 0
      - uses: actions/upload-artifact@v4
        with:
          name: keygen
          retention-days: 1
          path: ./keygen
  test:
    name: test-${{ matrix.on }}
    container: ${{ matrix.on }}
    strategy:
      matrix:
        on:
          - 'debian:stable'
          - 'debian:testing'
          - 'debian:unstable'
          - 'ubuntu'
          - 'fedora'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: keygen
          path: ./keygen
      - name: Dependencies (Debian/Ubuntu)
        if: ${{ startsWith(matrix.on, 'debian') || startsWith(matrix.on, 'ubuntu') }}
        run: |-
          apt-get update
          apt-get install -y --no-install-recommends openssh-client
      - name: Dependencies (Fedora)
        if: ${{ startsWith(matrix.on, 'fedora') }}
        run: |-
          dnf -y install openssh-clients
      - run: |-
          ls ./keygen
          chmod +x ./keygen/keygen
          stat ./keygen/keygen
          ./keygen/keygen 30s
